github:
  description: "Apache OpenOffice Project Website"
  homepage: "https://openoffice.apache.org/"
  labels:
    - openoffice
    - project
    - website
    - pelican

notifications:
  commits:      commits@openoffice.apache.org
  issues:       dev@openoffice.apache.org
  pullrequests: dev@openoffice.apache.org

pelican:
  notify:       commits@openoffice.apache.org
  autobuild:    true
  target:       asf-site
  theme:        theme/openoffice
  whoami:       main

staging:
  whoami:       asf-site
  profile:      ~

publish:
  whoami:       asf-site
