pelican:
  notify:       commits@openoffice.apache.org
  autobuild:    true
  target:       asf-site
  theme:        theme/openoffice
  whoami:       main

publish:
  whoami:       asf-site
  profile:      ~
